name: Deploy to VPS
on:
  push:
    branches: [ main ]
# test force
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          go install github.com/a-h/templ/cmd/templ@latest
          templ generate
          go build -o main .

      - name: Deploy to VPS via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22 # Ou ton port SSH
          source: "main"
          target: "/var/www/usine"
