name: Build and Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    # Utilise 'docker' ou 'ubuntu-latest', ce sont les labels standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          go install github.com/a-h/templ/cmd/templ@latest
          $(go env GOPATH)/bin/templ generate
          go build -o main .

      - name: Deliver
        run: cp main /output/main/output/main